name: clinica_psicologi
description: A new Flutter project.

# Previne publicação acidental em pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Seção de Dependências do Projeto
dependencies:
  flutter:
    sdk: flutter

  # Ícones de estilo iOS, adicionado para corrigir aviso de build
  cupertino_icons: ^1.0.6

  # Backend & Banco de Dados
  supabase_flutter: ^2.5.2

  # Utilitários e Formatação
  intl: ^0.19.0

  # UI - Calendário e Gráficos
  table_calendar: ^3.1.3
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.1.39

  # Geração de PDF
  printing: ^5.11.1
  pdf: ^3.10.8


# Seção de Dependências de Desenvolvimento
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


# Configurações específicas do Flutter
flutter:
  uses-material-design: true

  # Declaração da pasta de assets para que as imagens e fontes sejam encontradas
  assets:
    - assets/images/ # Agora esta linha aponta para a pasta 'assets/images' na raiz do projeto
    - assets/fonts/  # E esta para 'assets/fonts' na raiz do projeto


  # Declaração das fontes customizadas (se você as estiver usando)
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700